version: '3.8'
services:
    redis:
        image: redis/redis-stack-server
        ports:
          - "6379:6379"
    restapi:
      build:
        context: .
        dockerfile: ./Dockerfile.restapi
      ports:
        - "8080:80"
      depends_on:
        - redis
    counter:
      build:
        context: .
        dockerfile: ./Dockerfile.counter
      depends_on:
        - redis