# counter-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
spec:
  replicas: 1  # Start with 2 replicas
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
      - name: counter
        image: mvkan/keywords-counter-counter:latest 
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
        - name: REDIS_HOST
          value: redis  # The name of the Redis service
        
